CLA-CORPORATION
CLA-INDIVIDUAL
CONTRIBUTING
README.md

describing the project and pointing to contribution instructions.

Add CLA files, contribution documentation, and a README file

---

README.md

Adds descriptions of the various platform, binary, and script configuration needed on a development system to use the scripts in the SAS repository.

Update README.md with code prerequisites

---

data/ibfs/README.md
data/ibfs/ibfs.txt
src/data/extract_ibfs.py
src/data/retrieve_ibfs.py

The scripts retrieve the most recent version of the IBFS database
as well as extracting the entries of interest from the dataset.
FSS locations, frequency ranges, and coordination data (pointing
data) is extracted and transformed into the resulting CSV file.

Add scripts for retrieval and extraction of FCC IBFS data.

---

README.md

Add sources and installation instructions for jsonschema and pyopenssl modules.

Add jsonschema and pyopenssl dependencies

---

src/data/extract_ibfs.py
src/data/extract_ned.py
src/data/retrieve_ned_files.py

Also add an extraction script which pulls all needed geo files out of
zip containers for NED and NLCD.

Update NLCD retrieval script to include HI and PR.

---

src/.gitignore
src/prop/itm/itm.cpp

This follows discussions in Winnf Propagation TG on ITM parameters
and the handling of variability in the use we plan to make of the
model. See R2-SGN-03.

Change mdvar to 13

---

src/geo/land_use.py
src/geo/ned_indexer.py
src/geo/nlcd_indexer.py

Adds translation ability from NLCD code to WG1 Prop classifications.
Also adds the ability for the NED indexer to prepare elevation
profiles.

Fix bug in NLCD indexer on coordinate transformation.

---

schema/RegistrationRequest.schema.json

EUTRA_CARRIER_RSSI_NON_TX, EUTRA_CARRIER_RSSI_ALWAYS
Mark fields of GroupParam as required
E-UTRA should be E_UTRA

Correct enum values

---

src/geo/refractivity.py
src/geo/tropoClim.py

These scripts provide lookup functionality for the tropo climate and surface refractivity ITU data.

Lookup functions for climate and refractivity data

---

src/geo/ned_indexer.py
src/geo/nlcd_indexer.py
src/geo/refractivity.py

Also make changes to decrease printouts from other lookup
utilities and add Python module indicator files.

Fix NLCD indexer tile containment checks.

---

src/geo/nlcd_indexer.py

Moves handling of difference between gdal v1 and v2 to self.inv_txf method definition.

Support gdal v1

---

src/geo/nlcd_indexer.py
src/prop/model.py

This model incorporates adjustments to the ITM and eHata models
from WG1 Propagation task group, and combines the models using
the methods in NTIA TR 15-517.

Add a model for the integrated NTIA prop model.

---

src/geo/nlcd_indexer.py

Updates code to manage the different API signature for GDAL v1.

Handle GDAL v1

---

src/harness/testcases/registration_testcase.py

Single-Step registration (Cat A CBSD with no existing CBSD ID)

add SAS-CBSD registration test 10.3.4.1.2.1

---

src/harness/testcases/spectrum_inquiry_testcase.py

Implement WINFF.FT.S.SIQ.8 Missing cbsdId - spectrum inquiry

---

src/harness/testcases/spectrum_inquiry_testcase.py

Implement test case WINFF.FT.S.SIQ.9  Missing FrequencyRange object

---

src/harness/testcases/spectrum_inquiry_testcase.py

Parameters in inquiredSpectrum mutually invalid in spectrum inquiry

Implement WINFF.FT.S.SIQ.14

---

src/harness/testcases/spectrum_inquiry_testcase.py

Unsupported Spectrum (Error Code 300) for spectrum inquiry

Implement WINFF.FT.S.SIQ.15

---

src/harness/testcases/spectrum_inquiry_testcase.py

Both spectrum inquiry requests are for GAA channels

Implement WINFF.FT.S.SIQ.16

---

src/harness/testcases/spectrum_inquiry_testcase.py

cbsdId sent in the spectrumInquiry is different
from its assigned cbsdId, but the cbsdId does not exist in the SAS

Implement WINFF.FT.S.SIQ.12

---

src/harness/testcases/spectrum_inquiry_testcase.py

Two spectrum inquiry requests - One request successful and the other
unsuccessful

Implement WINFF.FT.S.SIQ.19

---

src/harness/testcases/grant_testcase.py

Request grant with lowFrequency and highFrequency value in
operationParam mutually invalid

Implement WINFF.FT.S.GRA.14

---

src/harness/testcases/grant_testcase.py

Request grant with frequency range specified
partially outside of the range 3550 MHz to 3700 MHz

Implement WINFF.FT.S.GRA.17

---

src/harness/testcases/grant_testcase.py

Request grant with frequency range specified
completely outside of the range 3550 MHz to 3700 MHz

Implement WINFF.FT.S.GRA.16

---

src/harness/testcases/spectrum_inquiry_testcase.py

Unsupported Spectrum (Error Code 300) when requesting spectrum inquiry

Implement WINFF.FT.S.SIQ.20

---

src/harness/testcases/spectrum_inquiry_testcase.py

Two spectrum inquiry requests; both requests unsuccessful

Implement WINFF.FT.S.SIQ.21

---

src/harness/fake_sas.py
src/harness/testcases/grant_testcase.py

Most of the code for GRA_11 is stolen from GRA_10.

Code for test case GRA_11 and the corresponding handler in fake_sas.

---

src/harness/testcases/registration_testcase.py

Removed an errant line / merge error. The [original PR](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/117) did not contain this line.

fix merge error on REG.12

---

src/harness/testcases/deregistration_testcase.py
src/harness/testcases/testdata/device_a.json
src/harness/testcases/testdata/device_b.json
src/harness/testcases/testdata/device_c.json
src/harness/testcases/testdata/device_d.json
src/harness/testcases/testdata/device_e.json
src/harness/testcases/testdata/device_f.json
src/harness/testcases/testdata/device_g.json

Fixed issue #171.
Also noticed that the conditional parameter measCapability was missing from the device json files. Added measCapability as a blank array for all devices.

Fix issue #171 DER.8

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py

Make interface to enable ppa zone definition calls

---

src/harness/sas.py

Few SAS - SAS Test Cases requires GET Request to Pull the Data. Created separate methods to either make a GET or POST Request.

Added Get and Post Request Methods

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py

Also Fixed Indentation for InjectWisp and InjectFss

Added SASAdministratorRecord Injection

---

src/harness/testcases/grant_testcase.py

GRA.1 Added Check for CBSD Category B
GRA.7 Added @winnforum_testcase decorator
GRA.12 Added 105 as a ResponseCode
GRA.23 Changed the device_b to device_c
GRA.26 Changed the device_b to device_c
GRA.27 Changed the device_b to device_c

Fixed Issues in Grant Testcases

---

src/harness/sas_interface.py

* Added decorator in InjectSasImplementationRecord  and InjectEscSensorDataRecord 
* Changed order of functions

Fixed Issues in Sas Interface

---

src/harness/testcases/deregistration_testcase.py
src/harness/testcases/relinquishment_testcase.py

* Changed the same devices in DRG.2, DRG.4 and RLQ.7
* Removed check for grantId in RLQ.7 as CBSD does not have a valid grant and this has been fixed in WINNF-15-S-0061 v0.6.5

Fixed Issues in DRG.2, DRG.4 and RLQ.7

---

src/harness/testcases/registration_testcase.py

Correct the longitude
Update test name

Patch REG_23, REG_26

---

schema/ContactInformation.schema.json
schema/EscSensorRecord.schema.json
schema/FccInformation.schema.json
schema/SasImplementationMessage.schema.json
src/harness/testcases/WINNF_FT_S_ESM_testcase.py
src/harness/testcases/WINNF_FT_S_SIR_testcase.py

* Added Pattern in JSONSchema for ContactInformation(Email), FccInformation(certificationDate, certificationExpiration and enum for sasPhase), and SasImplementationMessage (Id, URL)
* Added Assertion to Compare Dictionary in SIR.1 and ESM.1
* Formatting Changes

Fixed Issues in JSONSchema, SIR.1 and ESM.1

---

src/harness/util.py

Added support for cbsdReferenceId in ppaHelper Function as Cluster List API will be removed.

Added cbsdReferenceId in ppaHelper Function

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py

[will include the cluster list in the ppaInfo field]

Remove injectClusterList

---

src/harness/testcases/grant_testcase.py

Allowed channel widths for a Grant are 10, 15, 20, ... MHz

Modify GRA_28 for "allowed channel widths for Grant" rule

---

src/harness/testcases/grant_testcase.py

(PR 265 submitted for GRA_28 reversed this GRA_20 change)

Fixing GRA_20 again.

---

src/harness/testcases/grant_testcase.py
src/harness/testcases/spectrum_inquiry_testcase.py

(INVALID_PARAM -> INVALID_VALUE)

Correct error code strings

---

.gitmodules

Reverts Wireless-Innovation-Forum/Spectrum-Access-System#293

Revert "Add geodata submodule retrieved from WinnForum/SAS-Data repo."

---

src/harness/testcases/WINNF_FT_S_SIQ_testcase.py

NEW Spectrum Inquiry test cases using new IDs: 11.

---

src/harness/sas_testcase.py

Add InjectUserId to AssertRegistered() helper function.

Add InjectUserId to AssertRegistered() helper function

---

src/harness/testcases/WINNF_FT_S_HBT_testcase.py

heartbeat_testcase.py → WINNF_FT_S_HBT_testcase.py
Old HBT_2 → HBT_1

NEW Heartbeat test case using new IDs: 1.

---

src/harness/testcases/WINNF_FT_S_SIQ_testcase.py

(WINNF-TS-0061-V1.0.0-r14.0 dated 1 November, 2017)

Fix SIQ_11 to match the new spec revision 14

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py

adding API support for inject CPI user

add support for inject CPI user

---

src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
src/harness/testcases/testdata/device_i.json

Adding New SIQ #10.  Needed an extra Cat A device so added device_i.json

NEW SIQ test case using new ID: 10

---

src/harness/testcases/WINNF_FT_S_DRG_testcase.py

NEW Deregistration test cases using new IDs: 3, 4, 5
DRG3
DRG4
DRG5

NEW Deregistration test cases using new IDs: 3,4,5

---

src/harness/testcases/WINNF_FT_S_REG_testcase.py

NEW REG test case using new ID: 2

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py

NEW GRA test case using new ID: 4

assaneRed_GRA_4

---

src/harness/sas.py

added a check to see if a body is included in the JSON response from SAS under test

Updating sas.py to check whether to return data from API call

---

src/harness/testcases/WINNF_FT_S_HBT_testcase.py

NEW Heartbeat test case using new IDs: 5

NEW Heartbeat test case using new IDs: 5

---

src/harness/sas_interface.py

Accidentally introduced in PR#331

Fixing InjectCpiUser

---

src/harness/testcases/WINNF_FT_S_DRG_testcase.py
src/harness/testcases/WINNF_FT_S_HBT_testcase.py
src/harness/testcases/WINNF_FT_S_REG_testcase.py
src/harness/testcases/WINNF_FT_S_RLQ_testcase.py

Derive from sas_testcase.SasTestCase instead of unittest.testcase

Derive from sas_testcase instead of unittest.

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py

NEW GRA test case using new ID: 3

assaneRed_GRA_3

---

README.md
src/harness/README.md
src/harness/testcases/WINNF_FT_S_REG_testcase.py
src/harness/util.py

Old REG_7 → REG_3 
(InjectCpiUser is in PR#331)

NEW REG test case using new ID: 3

---

src/harness/testcases/WINNF_FT_S_RLQ_testcase.py

NEW RLQ test cases using new IDs: 3, 4

NEW RLQ test cases using new IDs: 3, 4

---

src/harness/reference_models/propagation/wf_itm.py
src/harness/reference_models/propagation/wf_itm_test.py

According to latest revision on R2-SGN-22.

Fix average calculation in ITM model.

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py
src/harness/testcases/WINNF_FT_S_MES_testcase.py
src/harness/testcases/testdata/meas_report_0.json

adding testcase WINNF_FT_S_MES_2

assaneRed_MES_2

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py
src/harness/testcases/WINNF_FT_S_MES_testcase.py
src/harness/testcases/testdata/meas_report_1.json

adding testcase WINNF_FT_S_MES_1

assaneRed_MES_1

---

src/harness/testcases/WINNF_FT_S_SIQ_testcase.py

Fix bug in siq_5:check availableChannel is present but not include PAL channel

assaneRed_Fix_SIQ_5

---

src/harness/testcases/WINNF_FT_S_REG_testcase.py
src/harness/util.py

[Based on Change Request: WINFF-17- I-00284
REG.5 and REG.6 test cases WINNF-TS-0061 V1.1.0 - Target Section:
6.1.4.5 and 6.1.4.6 ]

Fix REG_5.

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py

one code issue fixed for GRA 1 test

Fix Test Case GRA 1

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py
src/harness/testcases/testdata/device_h.json

Adding New GRA TCs 11 and 12.  Also added a device_h (new cat B CBSD)

NEW GRA test cases using new IDs: 11, 12

---

src/harness/sas.py
src/harness/testcases/WINNF_FT_S_HBT_testcase.py

# fix HBT.9 and merge of DPA methods

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py
src/harness/testcases/WINNF_FT_S_MES_testcase.py
src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
src/harness/testcases/testdata/fss_record_0.json
src/harness/testcases/testdata/grant_0.json
src/harness/testcases/testdata/gwbl_record_0.json
src/harness/testcases/testdata/gwpz_record_0.json
src/harness/testcases/testdata/meas_report_0.json
src/harness/testcases/testdata/meas_report_1.json
src/harness/testcases/testdata/spectrum_inquiry_0.json

Looked through the code and changed every xxxx.0 frequency or bandwidth value to xxxx

Changes to make frequency/bandwidth decimal values into integers

---

src/harness/testcases/WINNF_FT_S_REG_testcase.py

I'm getting some merge conflicts that look messy and i rather not risk messing the REG fiel so resubmitting on a new PR.  I Will delete PR351 once this is approved

Resubmitting REG8 on new PR (same as PR351) 

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py

GRA.1 is missing time import and will not run without it.

Fix missing import in GRA.1

---

src/harness/sas_testcase.py
src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
src/harness/testcases/helper_unit_testcase.py

Fix SIQ 4 and treat a corner case for helper function assertChannelsContainFrequencyRange

Update siq 4 and helper fuction

---

src/harness/util.py

Added an ability to update the Pal Record separately or Pal and Ppa Record together. This will be useful in PCR Test cases or in the execution of PPA Reference Model.

Updated the Make PPA and PAL Consistent Function

---

src/harness/testcases/WINNF_FT_S_DRG_testcase.py
src/harness/testcases/configs/test_WINNF_FT_S_DRG_6/default.config
src/harness/util.py

- Also includes the default.config
Note:
1. Need clarification on Step 5: CHECK: "If the corresponding request
contained a valid cbsdId the response shall contain the same cbsdId".
(I'll make the change in Line 410, once there is clarity. Right now the
test fails at that point, expecting a 103 and the actual being 102).
2. util.py is the same as in PR #407

New DRG test case using new ID: 6

---

src/harness/testcases/WINNF_FT_S_REG_testcase.py
src/harness/testcases/configs/test_WINNF_FT_S_REG_12/default.config

Also includes the generated config file.

NEW REG test case using new ID: 12.

---

src/harness/testcases/WINNF_FT_S_RLQ_testcase.py

Reference -WINNF-18-I-00053-RLQ.1 v2

Fix RLQ_1 per latest revision

---

src/harness/testcases/WINNF_FT_S_REG_testcase.py
src/harness/util.py

+ Removed duplicate REG.6 and REG.8 in WINNF_FT_S_REG_testcase.
+ Fixed order of REG.8.
+ Added log testcase header for configurable test cases as well.

Remove duplicate REG.6 & REG.8 & add log test case header to configurable testcase

---

src/harness/testcases/WINNF_FT_S_REG_testcase.py

If conditionalRegistrationData in config, then preload REG conditionals.

Check config before preloading REG conditionals.

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py
src/harness/testcases/configs/test_WINNF_FT_S_GRA_17/default.config

NEW GRA testcase using new ID: 17

---

src/harness/testcases/testdata/esc_sensor_record_0.json

Refer: https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/398

Use the installationParam object from SAS-CBSD 2.0

---

src/harness/testcases/WINNF_FT_S_MES_testcase.py

fix MES_2 to handle case where sas ask measReportConfig

assaneRed_Fix_MES_2

---

src/harness/util.py

remove duplicate getCertificateFingerprint

remove duplicate getCertificateFingerprint

---

src/harness/testcases/WINNF_FT_S_SDS_testcase.py

These tests were reviewed, approved and pushed in PR#425.
But they were wrongly deleted in PR#450 due to a bad merge operation.
Pushing again here the exact same tests.

Commit again SDS-6-10, 12-15 deleted in PR#450 due to a bad merge

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py

Also updated the copyright year and ordered the test cases.

Fix palRecords in GRA.17 - config.

---

src/harness/reference_models/propagation/wf_hybrid.py
src/harness/reference_models/propagation/wf_hybrid_test.py

According to spec change R2-SGN-22 (b).
Also perform some minor cleanup, such as:
-  not allowing the Hybrid model to be used for other reliability than 0.5 (median) and -1 (mean): exception instead of warning.
- some cleanup in the unit test

Implement fix of median to mean in Hybrid model.

---

src/harness/sas.py
src/harness/sas_interface.py

in sas.py and sas_interface.py

Remove the stuff relating to "SasImplementationRecord"

---

src/harness/testcases/WINNF_FT_S_HBT_testcase.py

- Make heartbeat_request to be a list
- Fix typo (comma) next to dpaId

Make heartbeat_request to be a list, fix typo

---

src/harness/sas_interface.py
src/harness/sas_testcase.py

Move the documentation from sas_interface to sas_testcase.

Move the documentation from sas_interface to sas_testcase.

---

src/harness/reference_models/geo/utils.py
src/harness/reference_models/geo/utils_test.py

To be used for PPA comparison according to eq 8.3.1 of test spec.

Add polygon comparison routines.

---

src/harness/reference_models/inter_sas_duplicate_grant/inter_sas_duplicate_grant.py

Preliminary implementation of peer SAS duplicate grant purging reference model for review.

peer SAS duplicate grant purging reference model

---

src/harness/reference_models/geo/utils.py
src/harness/reference_models/geo/utils_test.py
src/harness/reference_models/ppa/ppa.py

- Add winding check function
- Add winding correction function
- Add better conversion routines to geojson and shapely.
- Fix small bug in PolygonsAlmostEqual routine for dict input

Improve geo.utils module.

---

README.md
src/harness/README.md
src/harness/full_activity_dump.py
src/harness/full_activity_dump_helper.py
src/harness/full_activity_dump_helper_test.py
src/harness/full_activity_dump_integration_test.py
src/harness/full_activity_dump_test.py
src/harness/request_handler.py
src/harness/sas.py
src/harness/sas_test_harness.py
src/harness/util.py

This PR adds the Full Activity Dump Object. Additionally request handling has been refactored to its own file and the SAS test harness updated to produce FAD records matching the spec.

Full Activity Dump Object

---

src/harness/sas.py

Restores the QueryPropagationAndAntennaModel method to sas.py

Restore QueryPropagationAndAntennaModel method

---

src/harness/testcases/WINNF_FT_S_PAT_testcase.py

Adding indoor flag to wf_hybrid.CalcHybridPropagationLoss

missing indoor flag

---

src/harness/sas_testcase.py

- Fix registration_request documentation
- add cert, key changes that are in assertRegistered to assertRegisteredAndGranted too.

Correct the documentation for registration_request

---

src/harness/testcases/WINNF_FT_S_PPR_testcase.py

PPR.1 and 2 submission for review

---

src/harness/testcases/WINNF_FT_S_EPR_testcase.py

initial submission of EPR

---

src/harness/reference_models/examples/benchmark/time_dpa.py
src/harness/reference_models/examples/entities.py
src/harness/reference_models/geo/zones.py
src/harness/reference_models/geo/zones_test.py
src/harness/reference_models/ppa/ppa_test.py

- zones union of elements instead of MultiPolygon
which keeps only first polygon of inner MultiPolygons
- update ppa_test with the latest geo.utils
- fix issue introduced last minute in time_dpa
- massive speed up of the distribution when urban areas
- small improvements to the script

Fix small set of issues on previous #476

---

src/harness/testcases/WINNF_FT_S_GPR_testcase.py

GPR.1 through 3 submission for review

---

src/harness/testcases/WINNF_FT_S_EPR_testcase.py

Since ESC sensor location changed in FAD.1

Fixing device location - longitude

---

src/harness/testcases/WINNF_FT_S_SIQ_testcase.py

Injecting GWBL rather than GWPZ.

Small fix to SIQ3

---

src/harness/sas.py
src/harness/testcases/WINNF_FT_S_PCR_testcase.py

fix PCR.1 submission time mis-operation errors.

fix PCR.1 errors

---

src/harness/request_handler.py
src/harness/security_testcase.py
src/harness/testcases/WINNF_FT_S_SCS_testcase.py
src/harness/testcases/WINNF_FT_S_SDS_testcase.py

Fix SCS testcases by adding error code 403 for the first http request

assaneRed_Fix_SCS_testcases

---

src/harness/testcases/WINNF_FT_S_FPR_testcase.py

Create WINNF_FT_S_FPR_testcase.py

 WINNF_FT_S_FPR5  testcase

---

src/harness/request_handler.py
src/harness/testcases/WINNF_FT_S_HBT_testcase.py
src/harness/testcases/WINNF_FT_S_REG_testcase.py
src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
src/harness/testcases/WINNF_FT_S_SSS_testcase.py

- Fix broken test due to introduced HTTPError
- Introduce also a TLSError

Fix broken test due to introduced HTTPError

---

src/harness/testcases/WINNF_FT_S_FAD_testcase.py

According to the spec record type for coordination events is sas_record_type: coordination.

Update CoordinationEvent to coordination

---

src/harness/testcases/testdata/esc_sensor_record_0.json

See winnforum_sas/schema/InstallationParamEsc.schema.json for details.

Sets antennaAzimuth, which is a required field.

---

src/harness/testcases/WINNF_FT_S_SCS_testcase.py
src/harness/testcases/WINNF_FT_S_SDS_testcase.py
src/harness/testcases/WINNF_FT_S_SSS_testcase.py

http 403 fixes for SCS, SDS and SSS 11

jc s*s http403fix

---

src/harness/sas_test_harness.py

fix sas TH version, issue related to URLs/Version Seperation

fix sas TH version

---

src/harness/fake_sas.py

Adds TriggerFullActivityDump back into fake_sas.py (required to instantiate fake_sas). Minor fix please review.

Add TriggerFullActivityDump back into fake sas

---

src/harness/sas_testcase.py

Change 'TriggerDailyActivitiesImmediatelyAndWaitUntilComplete' to have the test case fail immediately if:
- the status check returns HTTP 500
- if any other error occurs 20 times in a row

Change 'TriggerDailyActivitiesImmediately...' to fail immediately  

---

src/harness/sas.py
src/harness/sas_interface.py
src/harness/testcases/WINNF_FT_S_EXZ_testcase.py

Initial submission of EXZ.2. Please review

EXZ.2 initial submission

---

src/harness/fake_sas.py
src/harness/sas.py
src/harness/sas_interface.py
src/harness/testcases/WINNF_FT_S_IPR_testcase.py

IPR.6 testcase

---

src/harness/reference_models/dpa/move_list.py
src/harness/reference_models/dpa/move_list_example.py

To be in line with other test harness code. No functionality change.
Just to avoid issues in the future with messing up the indentation.

DPA: Cleanup indentation of move_list module.

---

src/harness/testcases/WINNF_FT_S_IPR_testcase.py

IPR 3, 4 & 5 test cases do not require any knowledge of DPA movelists (assuming the config is valid). So have been put together in this PR.
Requires some of the changes to other files from the IPR.1 PR. Once IPR.1 is merged I will rebase this to be a change on top of it (This is not the case now as those changes would show up in the diff and make code review harder).

Initial IPR.3, IPR.4, and IPR.5

---

src/harness/fake_sas.py
src/harness/sas.cfg
src/harness/sas.py
src/harness/test_harness_objects.py

- Adds configurable maximum batch size for domain proxy

Add maximum batch size support

---

src/harness/reference_models/common/data.py
src/harness/reference_models/interference/aggregate_interference.py
src/harness/reference_models/pre_iap_filtering/fss_purge.py
src/harness/reference_models/pre_iap_filtering/fss_purge_test.py
src/harness/reference_models/pre_iap_filtering/inter_sas_duplicate_grant.py
src/harness/reference_models/pre_iap_filtering/pre_iap_filtering.py
src/harness/reference_models/pre_iap_filtering/pre_iap_filtering_test.py
src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_0.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_1.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_2.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_3.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_4.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_5.json
src/harness/reference_models/pre_iap_filtering/zone_purge.py
src/harness/reference_models/pre_iap_filtering/zone_purge_test.py

Previous version was developed and submitted while relying on old objects (no more existing in master).
Performed general cleanup without functionality change, and put it back on working order.

Pre-IAP : Fix and cleanup and fix Pre-IAP model.

---

src/harness/reference_models/iap/iap.py
src/harness/reference_models/iap/test_data/gwpz_0.json
src/harness/reference_models/iap/test_data/gwpz_1.json

using the standard GWPZ data format

---

src/harness/testcases/WINNF_FT_S_QPR_testcase.py

Changes to reg and grant request - format issue.

---

src/harness/reference_models/common/data.py
src/harness/reference_models/interference/aggregate_interference.py
src/harness/reference_models/interference/aggregate_interference_example.py
src/harness/reference_models/interference/aggregate_interference_test.py
src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
src/harness/testcases/WINNF_FT_S_GPR_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py

- Update reference model for aggregate interference to use CbsdGrantInfo
- Miscellaneous fixes for MCP.1 (from PR #617).
- Added land category calculation for GWPZ in MCP/XPR
- Corrected GWPZ file usage

MCP.1 fixes

---

src/harness/testcases/WINNF_FT_S_FDB_testcase.py
src/harness/testcases/WINNF_FT_S_WDB_testcase.py

fix injectDatabaseUrl errors found CommScope.

fix injectDatabaseUrl errors

---

cert/openssl.cnf

- remove duplicate [cps] section
- remove FRN from certificatePolicies, as it is not a role
- correctly set the FCCID/SERIAl as subjectAltName component

Clean openssl config file

---

src/harness/testcases/WINNF_FT_S_EPR_testcase.py
src/harness/testcases/WINNF_FT_S_FPR_testcase.py
src/harness/testcases/WINNF_FT_S_GPR_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py
src/harness/testcases/WINNF_FT_S_PPR_testcase.py

... and fix the default configs where necessary.

Add extensive checking of the MCP and xPR configs.

---

src/harness/reference_models/interference/test_data/gwpz_0.json
src/harness/reference_models/interference/test_data/gwpz_1.json
src/harness/reference_models/interference/test_data/gwpz_2.json
src/harness/reference_models/interference/test_data/gwpz_ut.json
src/harness/reference_models/pre_iap_filtering/fss_purge.py
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_0.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_1.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_2.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_3.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_4.json
src/harness/reference_models/pre_iap_filtering/testdata/cbsd_5.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_0.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_1.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_2.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_3.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_4.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_5.json
src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_bkp.json
src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_0.json
src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_1.json
src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_2.json
src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_3.json
src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_4.json
src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_5.json

Bug fix on fss_purge to get the registration instead of registrationRequest field.
Fix all unit test json with proper "registration" instead of "registrationRequest"

Fix unit test broken by recent PR + bug fix

---

src/harness/reference_models/dpa/dpa_mgr.py
src/harness/reference_models/geo/zones_test.py
src/harness/testcases/WINNF_FT_S_GRA_testcase.py
src/harness/testcases/WINNF_FT_S_HBT_testcase.py
src/harness/testcases/WINNF_FT_S_IPR_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py
src/harness/testcases/WINNF_FT_S_SIQ_testcase.py

Names for coastal DPAs need to use the latest naming scheme #625

Names for coastal DPAs need to use the latest naming scheme #625

---

README.md
src/harness/reference_models/common/mpool.py
src/harness/test_main.py

The code was not supporting mono-cpu, andthis would lead to an error.

Fix mpool to support mono-cpus.

---

src/harness/reference_models/propagation/itm/its/itm.cpp

Add definition of M_PI which is unknown for some compilers.

ITM: Minor fix for multi-compiler support.

---

src/harness/testcases/WINNF_FT_S_IPR_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py

and update MCP to use 1 arcsec

Update IPR (Issue #626) and MCP to support configs with zero test harnesses

---

src/harness/reference_models/common/data.py
src/harness/reference_models/interference/aggregate_interference.py
src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
src/harness/reference_models/pre_iap_filtering/zone_purge.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py

- Corrects data access for reference models
- Remove the use of duplicate code in `pre_iap_util`

Reference Model Fixes to support MCP

---

src/harness/certs/generate_sas_cert.sh

Script to help ITS with cert generation for SAS UUTs

Cert generation script for SAS UUTs

---

src/harness/testcases/testdata/grant_3.json

Add a missing zero to grant_3

---

src/harness/util.py

Modified logic to use intersection

filterChannelsByFrequencyRange fix

---

src/harness/reference_models/ppa/ppa.py
src/harness/reference_models/tools/testutils.py
src/harness/testcases/WINNF_FT_S_BPR_testcase.py
src/harness/testcases/WINNF_FT_S_PAT_testcase.py
src/harness/testcases/WINNF_FT_S_QPR_testcase.py

Fixed for : 
- PPA creation
- test cases BPR, QPR and PAT
Also fixed a small bug in PPA creation: beamwidth is optional for CatA so support this.
Finally minor cosmetic cleanup on indentation not right.

Fix for AMSL not taken into account (PPA creation, BPR, QPR and PAT)

---

src/harness/sas_testcase.py

Porting the changes that were previously done to CPAs over to PPA so the TH will not be as harsh should the SUUT missed any of the "are we there yet?" API checks

Changes to PPAcreation so API is more permissive

---

src/harness/testcases/WINNF_FT_S_PAT_testcase.py

the ppa.nlcd_driver was just a proxy so removed. W
e should use the drive.nlcd_driver instead.

Fix broken PAT following missing nlcd_driver reference

---

src/harness/reference_models/dpa/dpa_builder.py

Cleanup remaining debug ipdb trace in ported code from #675

DPA: Remove debug trace

---

cert/openssl.cnf
src/harness/certs/generate_fake_certs.sh
src/harness/testcases/WINNF_FT_S_EPR_testcase.py
src/harness/testcases/WINNF_FT_S_FPR_testcase.py
src/harness/testcases/WINNF_FT_S_GPR_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py
src/harness/testcases/WINNF_FT_S_PPR_testcase.py

Generate certs for each CBSD in testdata, use these in MCP/xPR default configs

---

src/harness/testcases/WINNF_FT_S_GRA_testcase.py

Fix GRA.13 to check lessEqual instead of less

---

src/harness/reference_models/iap/test_data/esc_0.json

Also please check if we need to do the same fix for 
src/harness/testcases/testdata/esc_sensor_record_0.json

fix the azimuthRadiationPattern setting error (issue #685)

---

src/harness/reference_models/interference/interference.py
src/harness/reference_models/interference/interference_test.py

PR #667 is a proposal to fix the FSS mask loss, which still has bugs according to me.
Because of disagreement on the remarks made on #667 , here is my proposed PR to fix the FSS Mask loss. In addition of fixing the reported bugs, it should also be much faster to run.
A unit test file is also added. Note that all the tests performed here fails in the other proposed solution.

FSS mask: alternative proposal to fix FSS mask loss.

---

src/harness/reference_models/interference/interference.py

Was loggin "region" instead of "region_type". This cause the code to fail.
Also fixed the doc using region_type everywhere for consistency.

Minor fix issue caused by recent addition of logging.

---

src/harness/reference_models/dpa/dpa_mgr.py
src/harness/reference_models/dpa/dpa_mgr_example.py
src/harness/reference_models/dpa/move_list.py
src/harness/reference_models/dpa/move_list_example.py
src/harness/reference_models/dpa/move_list_test.py
src/harness/reference_models/geo/zones.py
src/harness/reference_models/geo/zones_test.py

Removal of obsolete features related to neioghborhood (HAAT, exclusion_zone)
Support of the 4 neighborhood distance for catA, catB and OOB catA, catB.

DPA: update to comply with latest spec

---

src/harness/reference_models/interference/aggregate_interference.py
src/harness/reference_models/interference/interference.py

Previous PR has introduced logging for helping diagnose issues
but some of them are excessive in the amount of log generated.
Replace with upper level logging.

Remove/replace some of the logging.

---

src/harness/testcases/WINNF_FT_S_MCP_testcase.py

- Fixes the race condition introduced in PR #690.
- Threads will now produce more readable stack traces in the event of an exception, as well as stopping execution of the testcase.
- Adds logging for when concurrent processes have completed.

Fix MCP.1 race condition

---

src/harness/reference_models/geo/tropoclim.py
src/harness/test_main.py

Remove dead debug code in test_main.py : in order to avoid confusion
Fix a tropoclim utility routine, unused in test harnes, but useful for interactive analysis of climate.

Minor fixes - no effects on test harness

---

src/harness/util.py

...by ensuring that the PAL records and the PPA record have the same time range.

Fix flakiness in test cases which inject PPAs

---

src/harness/reference_models/interference/aggregate_interference.py

An extra comma was affacting the PPA log.

Fix typo in previous commit related to logs

---

src/harness/testcases/WINNF_FT_S_EPR_testcase.py
src/harness/testcases/WINNF_FT_S_FPR_testcase.py
src/harness/testcases/WINNF_FT_S_GPR_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py
src/harness/testcases/WINNF_FT_S_PPR_testcase.py

These are the changes agreed upon in this morning's WG4 call (see the WG4 mailing list for the latest draft).

MCP updates

---

src/harness/testcases/WINNF_FT_S_FDB_testcase.py

- Moves the CBSD in FDB.3 to a location where it can cause sufficient interference to be terminated.
- Inject the FSS database url in FDB.3

Correct FDB.3 default config, and add database url injection

---

src/harness/certs/generate_sas_cert.sh

Use all extensions during SAS cert generation.

---

src/harness/reference_models/dpa/dpa_mgr.py
src/harness/reference_models/geo/zones.py
src/harness/testcases/WINNF_FT_S_IPR_testcase.py

... and add logging to existing test cases.

Update IPR test cases according to the latest spec changes

---

src/harness/reference_models/geo/utils.py
src/harness/reference_models/geo/utils_test.py

- Reduce the floating point accumulation errors.
- Make sure border points are included in falling exactly on multiple of resolution, even given the small floating point errors.

Improve GridPolygon.

---

src/harness/testcases/WINNF_FT_S_MCP_testcase.py

Current logging for IAP aggr interference checking is way too expensive (logging every point), causing the log file to be too large and difficult to handle.
Notice that this change was already proposed, accepted and checked in PR #740, but got accidentally reverted in PR # 741 due to a merge issue. Current PR is a simple copy-paste of these changes.

Improved logging for IAP aggregation interference checking

---

src/harness/reference_models/geo/utils.py
src/harness/reference_models/geo/utils_test.py

the two cases treated in the intersection with canadian border are linestring & multi linestring.
the other cases are not treated and I don't think they can happen e.x.if the intersection is only one point.

Fix BPR.2 Issue by adding Multi_lineString case

---

src/harness/testcases/WINNF_FT_S_PAT_testcase.py

Fix PAT test case after Chris Anderson's bug report (https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/768).

Fix Chris Anderson's issue #768

---

src/harness/reference_models/dpa/README.md
src/harness/reference_models/dpa/dpa_builder.py
src/harness/reference_models/dpa/dpa_mgr.py

Improve the documentation for the dpa package, as it has not been updated since the early days 
of the move_list.py only module done by NIST.

Fix documentation for DPA.

---

src/harness/sas_testcase.py

removed incorrect code in sas_testcase.py

Paul from red fixed incorrect code in sas_testcase.py

---

src/harness/testcases/WINNF_FT_S_PPR_testcase.py

align the grants frequencies with the PPA frequencies

PPR_1 default config file update 

---

src/harness/testcases/WINNF_FT_S_MES_testcase.py

Update the MES.2 test case to remove CBSD #5 as requested by WG4.

Update the MES.2 test case to remove CBSD #5 as requested by WG4.

---

src/harness/security_testcase.py

Prior to this commit, assertTlsHandshakeFailure was missing a call to
load_verify_locations(). The CRL tests (SxS_11 and SxS_16) simply
detected an unknown server certificate, and didn't progress to the point
of detecting a revoked client certificate.
By checking for success and failure using a common function, we can be
more confident that the test is correct.
Fixes #488

Refactor assertTlsHandshake{Succeed,Failure} into a common function.

---

src/harness/testcases/WINNF_FT_S_QPR_testcase.py

p/10 is integer division. Change to floating point.

Minor numerical correction in QPR testcase

---

src/harness/testcases/WINNF_FT_S_IPR_testcase.py

Implement changes to IPR.7 requested by WG4.

Implement changes to IPR.7 requested by WG4.

---

src/harness/test_harness_objects.py

Batch domain proxy registration and heartbeat requests with maximum batch size.

Domain proxy batching of registration and heartbeat

---

src/harness/testcases/WINNF_FT_S_PAT_testcase.py

The current test code causes the PAT test to fail as soon as the failure threshold is reached. While this can save time if you want only a pass/fail result for a SAS, it makes debugging difficult: the debugger typically wants to get the maximum amount of data from each test run, and in that case the early-exit feature is counterproductive. ITS recently noted the drawbacks of our overly-eager optimization, so this PR introduces a flag which lets them toggle between the two modes (with the default being to disable early-exit).

Introduce a flag to turn on/off early-exit in PAT

---

src/harness/sas_testcase.py
src/harness/testcases/WINNF_FT_S_FAD_testcase.py
src/harness/testcases/WINNF_FT_S_GRA_testcase.py
src/harness/testcases/WINNF_FT_S_MCP_testcase.py

Change based on Issue 799
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/799#issuecomment-421357895

Whitelist fccIds by injecting before FAD

---

src/harness/test_harness_objects.py

ITS has requested this change to account for differences in SAS behavior during registration. The change allows the test harness to ignore registration failures and continue test execution, whereas previously a registration failure would immediately cause a test case failure. Registration failures will be logged so that unexpected or widespread registration failures can be detected. This change is consistent with the test spec.

Update MCP testcase to ignore failed registrations

---

src/harness/reference_models/dpa/dpa_mgr.py

There are no functional changes in this PR. Instead, it adds logging for A_DPA and A_DPA_ref for every DPA point at every azimuth. It also adds logging of statistics on their difference.

Add more logging of A_DPA, A_DPA_ref, and keep lists to DPA manager

---

src/harness/util.py

Fix error creating PAL record for FIPS codes with leading zeroes

---

src/harness/util.py

Improve portability of JSON schema checking code

---

src/harness/reference_models/pre_iap_filtering/fss_purge.py

Do not apply FSS purge list when FSS high frequency is below 3700 MHz

# Filter FSS with high frequency below 3700 MHz for purge list calculation

---

src/harness/reference_models/dpa/move_list.py
src/harness/reference_models/propagation/wf_itm.py

fix move list when CBSD position is at same location of the protected point, the calculation of pathloss return a value(0), so for this case we form an array(with same length as reliabilities) of interferencex of the same value.

small fix of move list when CBSD position is at same location of the protected point

---

src/harness/testcases/WINNF_FT_S_MCP_testcase.py

Check for always activated DPA frequency range. Activation is not triggered for such DPAs

check for always activated DPA frequency range

---

src/harness/test_harness_objects.py
src/harness/testcases/WINNF_FT_S_PPR_testcase.py

This PR implements the new PPR.3 test case which was approved last week in WG4. Although it makes changes to the DomainProxy object, the changes are strictly additions and hence no other test cases are affected.

Implement PPR.3

---

data/ntia/README.md

So that it reflects accurately the status of file of the related directories

Documentation: update stales README

---

src/harness/reference_models/tools/cpirid_dedupe.txt

Included as a logic reference to implement the same de-dupe process in SAS

CPIR-ID database de-dupe

---

data/ntia/E-DPAs.kml

Characterized by a OOB Neighborhood for CatB set to 0 (like catA).
This follows DoD agreement to suspend OOB operations for the time
being until more precise live evaluation of the interference
environment.

New DPA v1.08

---

src/harness/reference_models/propagation/p2108.py
src/harness/reference_models/propagation/p2108_test.py

Add implementation of P.2108 defined clutter loss to reference_models/propagation

Add calc P.2108

---

src/harness/reference_models/propagation/p2108.py
src/harness/testcases/WINNF_FT_S_PAT_testcase.py

I added PAT.2 test with default config and I added modelType to PAT.1 configs. Added `ACTIVITY_LOSS_FACTOR` to p2108 file but I can move it to a more appropriate file if one exists.

Add PAT.2 test case

---

src/harness/testcases/WINNF_FT_S_PAT_testcase.py

Change needed to make fake-sas work for the new test PAT-2

make sure fake-sas works for PAT_2

---

src/harness/reference_models/dpa/dpa_mgr.py
src/harness/reference_models/dpa/move_list.py
src/harness/reference_models/dpa/move_list_test.py
src/harness/reference_models/geo/zones.py

Add OOB DPA distances to updated neighborhood neighbor_distances
Update catBOOBNeighborhoodDistanceKm default distance to 0

DPA updated neighborhoods OOB handling, cat B default 0

---

data/configs/test_WINNF_FT_S_IPR_8/IPR-08.white_sands_missile_range.draft.20240312.config
data/configs/test_WINNF_FT_S_IPR_8/IPR.08.west14.default.20240305.config
data/configs/test_WINNF_FT_S_PAT_2/pat2.default.20240212-4.config

Add PAT.2 and IPR.8 configs generated by Sony.

Add configs for PAT.2 and IPR.8 from Sony

---

src/harness/testcases/WINNF_FT_S_PAT_testcase.py

Write PAT.2 results to an output CSV file in `testcases/output` directory. File name includes config file used and each row in the CSV contains the PAT request and response details.

Save PAT.2 config and results to output file

---

src/harness/reference_models/common/data.py

Update common/data.py constructCbsdGrantInfo to continue handling case where grant_request is None for cbsd_id field added in pull request 922.

Update common/data.py constructCbsdGrantInfo
