CONTRIBUTING
Updated to reference the WinnForum IPR policy document as
governing the repository and requiring contributors to
be members or observers.
=> Update the CONTRIBUTING file with IPR reference.

src/prop/itm/itm.cpp
This change was discussed with NIST in Sept 2016. The value for
this parameter as used by NTIA in their model was 3 instead of 12.
=> Modify mdvar parameter from 12 to 3.

src/data/retrieve_ned_files.py
This file contains a retrieval script which fetches the appropriate terrain and land cover tiles from government sources corresponding to the 1-arc-second NED terrain tiles and the NLCD data files for land cover.
=> Add retrieval script for terrain and land cover data

src/data/retile_nlcd.sh, src/data/retrieve_ned_files.py
Substantial filtering added to only retrieve needed US-intersecting and nearby NED tiles.
Added a script to retile the large NLCD datasets to more manageable tiled versions.
=> Only fetch US tiles of NED. Script to retile NLCD data files.

src/prop/ehata/ehata.py, src/prop/itm/itm.cpp, src/prop/itm/itm_py.cpp, src/prop/itm/pytm.py, src/prop/itm/test_itm.py
Also add changes to ITM wrapper to do better bounds checking
and bad values detection, and accept output from cases where
warnings are found with parameter values (ITM marks a pretty
wide variety of inputs as resulting in less accurate output.)
=> Fix bug in eHata rolling hills correction; add py ITM wrapper

src/prop/model.py
The effective height of the CBSD is the only criterion, not the effective height of the other end, according to R2-SGN-04. Note that this means that the first point (lat1, lon1, h1) must always correspond to the CBSD, not the PPA or GWPZ.
=> Only CBSD effective height considered

src/prop/model.py
The comparison to 200 m is based on effective heights instead of actual heights. Modified code accordingly. ***Note: profile[] is now calculated as many as three times in this code for each path. Should we just declare it as a global variable and calculate once at the beginning, or implement another way to do it so we're not creating the same profile three times?
=> Added effective heights calculation

src/harness/testcases/registration_testcase.py
The test case does not compare the recorded CBSD IDs with the re-registered CBSD IDs, but I think it should. I will propose this change in the spec.
self.assertTrue(cbsdId1 == response['registrationResponse'][0]['cbsdId'])
self.assertTrue(cbsdId2 == response['registrationResponse'][1]['cbsdId'])
=> add registration test WINFF.FT.S.REG.9

src/harness/testcases/spectrum_inquiry_testcase.py
Two registration calls being made when only one should be.
=> Correct SIQ.21

src/harness/testcases/grant_testcase.py
Both requests are for GAA channels, no incumbent present in the GAA frequency ranges used in the two requests.
=> Implement WINNF.FT.S.GRA.21, WINNF.FT.S.GRA.22 and WINNF.FT.S.GRA.23

src/harness/testcases/registration_testcase.py
REG.4: test spec does not require us to check that it's the same CBSD ID (line 199)
REG.10: should also check that there is no CBSD ID in the response
REG.12: should the error code be 200 instead of 103?
REG.22: according to the test spec, we don't need to check that there is no CBSD ID in the third response
=> fixes to REG.4, REG.10, REG.12, REG.22

src/harness/fake_sas.py, src/harness/testcases/registration_testcase.py
1. fix REG.21 to pass array [device_a] for registrationRequest instead of device_a
2. Change line 200 to respond with 404 instead of 400 (it makes more sense *and* it will cause the "bad version number" tests to start passing).
Update if/else tree which starts on line 183 as follows (which will get rid of the errors in REG.{1,2,3,4,5,11,14,15,16,26}):
elif self.path in ('/admin/reset', '/admin/injectdata/fccId', '/admin/injectdata/registration'):
response = ''
=> fix REG.21 & allow more tests to pass with fake SAS

src/harness/testcases/registration_testcase.py
Valid characters are defined in RFC-7542 Section 2.2 as below. For example, the '(' character is not one of the allowed characters. "^" is also allowed.
Allowed characters are identified as
Formal Syntax
The grammar for the NAI is given below, described in Augmented
Backus-Naur Form (ABNF) as documented in [RFC5234].
nai            =   utf8-username
nai            =/  "@" utf8-realm
nai            =/  utf8-username "@" utf8-realm
utf8-username  =  dot-string
dot-string     = string *("." string)
string         = 1*utf8-atext
utf8-atext     =  ALPHA / DIGIT /
"!" / "#" /
"$" / "%" /
"&" / "'" /
"*" / "+" /
"-" / "/" /
"=" / "?" /
"^" / "_" /
"`" / "{" /
"|" / "}" /
"~" /
UTF8-xtra-char
utf8-realm     =  1*( label "." ) label
label          =  utf8-rtext *(ldh-str)
ldh-str        =  *( …
=> fix invalid character in REG_15, ^ is allowed, @ is not

src/harness/util.py
Probably we should keep using the json.loads(json.dumps(<Var Name>)) to convert into the normal dictionary from defaultdict because typecasting using dict is not working recursively when there's nested defaultdict.
=> Fixed Issue in PAL and PPA Helper Function

src/harness/testcases/testdata/pal_record_0.json, src/harness/testcases/testdata/ppa_record_0.json, src/harness/util.py
Removed censusInformation (fipsCode and censusYear) from PPA and added that into Pal Record with fccChannelId to allow multiple PALs.
=> Fixed ppa Helper function by adding censusInfo and channel in Pal Record

src/harness/testcases/testdata/ppa_record_0.json
Updated PPA Record File as censusYear and fipsCode is required in the Pal Record File based on the util.py(https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/util.py#L86)
=> Updated PPA Record File

src/harness/reference_models/examples/README.md, src/harness/reference_models/examples/entities.py, src/harness/reference_models/examples/example_fss_interference.py
One simple example is provided for FSS protection.
It exercises:
- Selecting CBSD within 150km of FSS
- Winnforum ITM propagation model
- antenna gain calculation for CBSD (Standard method with beamwidth only)
- antenna gain calculation for FSS
- obtaining all possible FSS pointing for given FSS license info
=> Provide example of reference_models usage.

src/harness/reference_models/antenna/antenna.py, src/harness/reference_models/antenna/antenna_test.py, src/harness/reference_models/antenna/fss_pointing.py, src/harness/reference_models/antenna/fss_pointing_test.py
Allows to compute antenna gain for CBSD, DPA (radar), ESC and FSS.
Also provides a routine to find the FSS possible pointing angles according to the licensed information (range of east/west elevation, azimuth and GSO arc longitude).
This is an extension of RedTechnologies  PullRequests of July with better integration in the reference_models/ framework developed since then.
=> Antenna reference code.

.gitmodules
Introduce the SAS-data repository as a submodule under data/geo.
Discussions within WinnForum led to the continuing use of Git LFS to hold the geo reference data (for NED and NLCD) but in a separate repository at: https://github.com/Wireless-Innovation-Forum/SAS-Data
This PR simply introduce the ability to see this repository as a GIT submodule under data/geo
=> Add geodata submodule retrieved from WinnForum/SAS-Data repo.

src/harness/sas.py, src/harness/sas_interface.py
Add fccMaxEirp as an optional parameter to the InjectFccId() function with a default value of 47 dBm/10 MHz.
=> Make fccMaxEirp an optional param in InjectFccId()

src/harness/reference_models/propagation/ehata/its/ehata.h
In particular some compiler based on LLVM (such as clang)
do not support "#pragma once" construct.
=> Small fix on ehata C++ code to support some compilers.

src/harness/reference_models/geo/terrain.py, src/harness/reference_models/geo/terrain_test.py, src/harness/reference_models/propagation/wf_itm.py, src/harness/reference_models/propagation/wf_itm_test.py
New function wf_itm.ComputeHaat().
Note: this is provided as part of  wf_itm which manages the terrain driver.
A future PR will have some cleanup so that the wf_itm module is the unique source of data drivers (currently duplicated in wf_hybrid).
=> Provide  HAAT calculation routine.

src/harness/reference_models/geo/vincenty.py, src/harness/reference_models/geo/vincenty_test.py, src/harness/reference_models/propagation/ehata/its/FindQuantile.cpp, src/harness/reference_models/propagation/itm/its/itm.cpp
Following discussion with FW, a few fixes are proposed:
- vincenty: when both points are identical position
- eHata: issue with FindQuantile: data access over range
- ITM: case of reliability/confidence 0.5 does not lead to
exact 0 value as expected.
=> Few fixes to the reference models.

src/harness/reference_models/geo/terrain.py, src/harness/reference_models/propagation/wf_hybrid_test.py, src/harness/reference_models/propagation/wf_itm_test.py
This is ongoing branch for fixes to reference models following various feedback from Winnforum participants.
- Fix the profile number of points to follow the spec (final resolution
shall be as close as possible as 30m without being higher). Reported by arhannan  in #361.
- Add a utility routine on the terrain driver to force the driver to
return all zero altitude. This is useful for testing/debugging, and was
done before by not pointing to a valid geo database. But recent change
on geo data robustness now prevent using that workaround. This new
method allows to recover this behavior by simply doing:
wf_itm.terrainDriver.SetFlatEarthMode(do_flat=True)
- Fix the unit testing
=> Bunch of small fixes on the reference models

src/harness/reference_models/geo/terrain.py, src/harness/reference_models/propagation/ehata/ehata.py
- process correctly terrain invalid values in non interpolation mode.
This does not affect current operation as terrain is always used as interpolated, but can eventually 
affect internal testing between real SAS and reference models.
- Remove a useless test in CbsdEffectiveHeight() (ehata/ehata.py).
This test is already part of wf_hybrid.py, and prevent the routine
to provide same result as internal effective height from C code, which
is useful for testing. Reported by Mayowa from Commscope.
=> Misc minor fixes to ref models

src/harness/sas.py, src/harness/util.py
Add logger to testcase decorator. Promote logging level of request/response messages to INFO.
Add a logger to ensure that logging is turned on, even when running only
one test case (e.g. with `python -m unittest`).
Promote logging of requests/responses to INFO level so that we can see
them without getting all of the curl debug messages at the same time.
=> Improve logging

src/harness/reference_models/propagation/ehata/its/ExtendedHata.cpp, src/harness/reference_models/propagation/ehata/its/FineRollingHillyTerrainCorectionFactor.cpp, src/harness/reference_models/propagation/ehata/its/PreprocessTerrainPath.cpp, src/harness/reference_models/propagation/ehata/its/ehata.h, src/harness/reference_models/propagation/wf_hybrid_test.py
Two fixes:
- Improve the path profile distance to recover floating point accuracy
loss (caused by the profile format where the distance is obtained
by a multiplication N.step, instead of being encoded). This may
cause mismatch on various compilers, because of the calculation
non-linearities dependent on specific 'plain' distance (10km...).
- use internal dynamic array instead of hardcoded one, which causes
crash if step resolution < 25m
NOTE: related to FW report: #333
=> E-Hata fixes for robustness

src/harness/reference_models/geo/terrain.py
The flat earth test mode of the terrain driver allows for simulation on
flat earth with zero altitude.
Unfortunately using zero altitude is detected by some model (E-Hata) as
the sea, and they apply a special correction increasing the pathloss.
To avoid confusion, the flat earth mode will now return a fixed altitude
of 10 meters to simulate being inland.
This does not affect normal operation as this is used only for tests.
=> Fix flat-earth test mode.

src/harness/sas.py, src/harness/util.py
1. Added formatter to test case logging so it would include timestamp and other fields from the test_main.py formatter. Having the timestamp (which defaults to a local timestamp, even if in a different timezone than SAS) will help in correlating SAS logs to Test Harness logs.
2. Added error description to the assert message, since that message sometimes contains more details than the number provides and could be useful for debugging.
a. Consolidated _RequestPost and _RequestGet, as the only difference is request is None for _RequestGet.
=> Improve logging - timestamp and error description

src/harness/reference_models/antenna/antenna.py, src/harness/reference_models/antenna/antenna_test.py
The spec allows for such extrema values without clear specification
of the behavior. Clearly when those happens, we should consider the
antenna as omnidirectional.
=> Fix antenna gain when beamwidth is 0 or 360 degrees.

src/harness/util.py
Only add a logging handler if none have been added. So logging will be configured whether running one testcase or running testcases using test_main.py, which also adds a logger.
=> fix logging handler being added every time a test case is invoked

src/harness/reference_models/geo/utils.py, src/harness/reference_models/geo/utils_test.py
Useful to efficiently grid a zone from a GeoJSON or a Shapely
polygon (PPA, DPA, ...).
=> Add a new utility routine GridPolygon().

cert/openssl.cnf, src/harness/certs/generate_fake_certs.sh
This PR is to address the issues found by Tahashi of Sony.
[1] SCS.10
-line 234 :    -policy policy_anything -extensions sas_req_sign -config ../../../cert/openssl.cnf \
Comment: 
This will create cert of the wrong usage (serverAuth). 
I’ve Looked into the openssl.cnf file and I believe the correct way is: 
-policy policy_anything -extensions wrong_cbsd_req_sign -config ../../../cert/openssl.cnf \
[FW] We agree with this comment and the TLS authentication will fail for the wrong usage. We will use sas_client_mode_req_sign instead of wrong_cbsd_req_sign. I think that will be correct approach. Both wrong_cbsd_req_sign and sas_client_mode_req_sign are exactly the same. Both will create a SAS certificate with usage clientAuth. sas_client_mode_req_sign
was added to address the usage issue.
[2] …
=> fix SCS.10 and SDS.10 issues

src/harness/sas_test_harness.py
adding "cbsd/" prefix in generateCbsdReferenceId() helper function per reviewer's suggestion.
=> adding "cbsd/" prefix in generateCbsdReferenceId()

cert/openssl.cnf, src/harness/CRLServer-README.md, src/harness/certs/generate_fake_certs.sh, src/harness/certs/revoke_and_generate_crl.sh, src/harness/simple_crl_server.py
This is a Python implementation of simple CRL server (a.k.a CDP) using native openssl CRL capabilities for test cases like SCS/SDS/SSS.11, SCS/SDS/SSS.16. This server is a light-weighted but fully capable CRL server implemented using Python. The server can be deployed and run independently or can be included in the test codes run -- depends on final decision. 
This is the proposed solution for providing such CRL server capabilities to the ITS in supporting the corresponding test runs. Please review.
A reference of the openssl CRL capabilities can be found in https://jamielinux.com/docs/openssl-certificate-authority/certificate-revocation-lists.html
=> Simple CRL server using native openssl CRL capabilities

src/harness/reference_models/interference/interference.py
We split the interference module out of IAP PR as suggested by reviewers. This module is used in FSS purge list reference model and IAP reference model. Please review, Thanks.
=> split the interference module out of IAP per reviewer's suggestion

src/harness/testcases/WINNF_FT_S_GRA_testcase.py
Injecting FCC IDs into SUUT before SUUT does CPAS and gets a FAD that includes them, otherwise SUUT will not know about them.  When we go to register the CBSDs on the next step the FCC IDs will get injected again but the SUUT should just overwrite them without an error
=> Injecting FCC IDs for GRA5 before CPAS so SUUT will know about them 

cert/openssl.cnf, src/harness/certs/README.md, src/harness/certs/generate_fake_certs.sh, src/harness/certs/revoke_and_generate_crl.sh, src/harness/fake_sas.py, src/harness/simple_crl_server.py, src/harness/testcases/README.md, src/harness/testcases/WINNF_FT_S_SCS_testcase.py, src/harness/testcases/WINNF_FT_S_SDS_testcase.py, src/harness/testcases/WINNF_FT_S_SSS_testcase.py
As WinnF WG.2 and ITS approved to use CRL as the initial certificate blacklisting solution before OCSP is available, the test codes developers working on security related test cases came to the following agreements:
1. Deploy a CRL server (a.k.aThe certificate revocation list distribution point – CDP) in the ITS designated VM environment to serve as a FCC certification dedicated CRL server
2. Certificates, sub-CAs to be blacklisted for all the test cases (e.g. SCS.11 and SCS.16 etc.) will be created and per-loaded into the CRL server appropriately. There is NO need for the test harness codes to blacklist a certificate or sub-CA on-demand. During the test, the test codes will directly use the certificate or sub-CA that are already in the CRL.
3. SAS UUT is assumed to pull the CRL …
=> SCS/SDS/SSS.16 implementation based on WG.2 confirmation -- revoked CA is sub-CA

src/harness/full_activity_dump_helper_test.py, src/harness/sas.py, src/harness/sas_testcase.py, src/harness/security_testcase.py, src/harness/test_harness_objects.py, src/harness/testcases/WINNF_FT_S_IPR_testcase.py
- Initial IPR.1 testcase (Note: The DPA movelist initialization and access methods will almost certainly be changed, as will the default config, at present it is just an example and probably does not include CBSDs in a DPA).
Minor fixes:
- Move default cert function out of sas object, so they may be used by other objects (In this case domain proxy).
- Make sas testcase assertRegistered check the length of responses matches the length of requests.
- Add conditional registration data support to domain proxy.
- Allow domain proxy to use default certs (Note: This modifies the domain proxy init interface).
=> Initial IPR.1 testcase

src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Fix certificate injection to be from config file for SSS.18 instead of default certificate. Otherwise, the SAS peer injected and the FAD request to that SAS peer could have different certificates.
=> SSS.18: fix certificate injection

src/harness/sas.py, src/harness/test_harness_objects.py
Changes the ```getDefault*Path``` functions to ```GetDefault*Path```. This is consistent with the rest of the file and what most of the code assumes.
=> Fix default cert function name

src/harness/full_activity_dump_helper.py
Fix per Sony's review comment in "Tests Review Notification (full_activity_dump_helper.py in master)" on the 17th of April.
Corrects the full activity dump helper to request a FAD using the given cert/key, previously the cert/key was passed but never used.
=> Fixed FullActivityDumpHelper to correctly use the ssl cert/key

src/harness/sas.py
...times in the same test case.
=> Avoid injecting the same FCC ID / User ID multiple

src/harness/reference_models/propagation/wf_hybrid.py, src/harness/reference_models/propagation/wf_hybrid_test.py, src/harness/reference_models/propagation/wf_itm.py, src/harness/reference_models/propagation/wf_itm_test.py
As proposed in WG1 specification change (note: not yet integrated in spec), to use minimum of 1m height.
Also add following changes:
- remove the exception check for maximum height
- add a flag parameter to specify if CBSD height is a AMSL height. Using this flag will simplify the test harness code logic, as it wont need to do the test for AMSL and correction in various places. 
Background:
The models are not designed for negative height, and would return bogus results.
Normally AGL height should always be positive (except for CBSD in basement or tunnels or subway), although an error in configuration would go through the SAS-CBSD protocol. 
Problematic also is the height being specified as AMSL. This AMSL would be transformed into an AGL height by removing the terrain height coming from …
=> Prop Models: Implement minimum height of 1m

src/harness/testcases/WINNF_FT_S_HBT_testcase.py, src/harness/testcases/WINNF_FT_S_REG_testcase.py, src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
The following testcases need updated sas cbsd version variable names:
RLQ.4
REG.10
REG.13
HBT.3
self._sas._sas_version should be self._sas.cbsd_sas_version
Also, REG.10, REG.13, and RLQ.4 set the CBSD SAS version to a higher version, but do not put the version back. Added the logic to put the version numbers back to the original config version.
=> fix sas version variable name

src/harness/security_testcase.py, src/harness/testcases/WINNF_FT_S_SSS_testcase.py
1. src/harness/security_testcase.py
These changes are to ensure the Peer SAS injection occurs before TLS checks.
Move code from line 188 to line 196: 
self.assertTlsHandshakeSucceed(self._sas_admin._base_url, [cipher],
client_cert, client_key)
2. src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Test harness injects Peer SAS fingerprint's for config['sasCert'] but then performs original line 369 for TLS handshake success using SAS_CERT. This will never succeed because only config['sasCert'] has fingerprints in the SAS UUT, so line 369 should be changed to use config's key and certificate.
original: 
self.assertTlsHandshakeSucceed(self._sas_admin._base_url, ['AES128-GCM-SHA256'], SAS_CERT, SAS_KEY)
proposed change: 
self.assertTlsHandshakeSucceed(self._sas_admin._base_url, …
=> A few security fixes

src/harness/testcases/WINNF_FT_S_FPR_testcase.py
Noticed that we use 2 peer SASs in these configs, but they use same certs.
This is also the case for similar testcases EPR, GPR, PPR.
Will address this issue in a separate PR.
=> Create config for FPR.2 and FPR.4 testcases

src/harness/reference_models/common/data.py, src/harness/reference_models/common/mpool.py, src/harness/reference_models/iap/iap.py, src/harness/reference_models/iap/iap_example.py, src/harness/reference_models/interference/aggregate_interference.py, src/harness/reference_models/interference/aggregate_interference_example.py, src/harness/reference_models/interference/aggregate_interference_test.py, src/harness/reference_models/interference/interference.py
This is one step of various cleanup to bring the ref models in a better coherent state.
In this step:
- reuse the common objects for GrantInfo, etc..
- migrate some objects in the common/data.py  (FssInfo and EscInfo)
- misc API cleanup by removing unused parameters
- misc cosmetic cleanup
Note: preliminary - will continue on the iap and pre_iap directory (note that this last one was left broken last week)
=> Reference model general cleanup - Part 1

src/data/resample_uscabdry.py, src/harness/reference_models/geo/terrain.py, src/harness/reference_models/geo/vincenty.py, src/harness/reference_models/geo/vincenty_test.py
This routine was returning data as a list of (lat,lon) points,
by zipping from the numpy vectors. However the main consumer routine (`TerrainProfile()`)
works directly in vectors so as to do the reverse unpacking, and reconvert to numpy vectors.
All this is inefficient and lead to a 10% speed loss on original code using about 3ms per ITM calc (and 20% on the code optimized for using 1.7ms per ITM calc), as I found out in line profiling. By returning directly the numpy vectors, we avoid a useless packing/unpacking operation.
Because this optimization is so simple, I propose it.
=> Small speedup:  GeodesicSampling routine.

src/harness/testcases/WINNF_FT_S_FAD_testcase.py
The current implementation of FAD.1's comparison gets a string of the FAD file contents and hashes it. The problem with this is the conversion from a dict to string with the json library is not guaranteed to be the same each time. The solution is simply to compare the dictionary objects themselves.
=> Change comparison for FAD.1 to compare the objects instead of hashing

src/harness/reference_models/common/mpool.py, src/harness/reference_models/ppa/ppa.py, src/harness/test_main.py
All modules (including PPA) now fully migrated to mpool.
Configuration of mpool on top executable file of the test harness.
Fix dummy mpool to be compatible `multiprocessing.Pool` and not `futures`.
=> Finalize multiprocessing cleanup.

src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Adjusted the FAD.2 test cases devices 1,2,3,4 to about 100 miters from the protected ESC sensor and PPA so that the aggregate interference is significant enough for validating the test case. Please review.
=> adjust device locations of FAD.2 to be closer to the protected entities

src/harness/testcases/WINNF_FT_S_EPR_testcase.py, src/harness/testcases/WINNF_FT_S_FPR_testcase.py, src/harness/testcases/WINNF_FT_S_GPR_testcase.py, src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Purely intending to help speeding up the MCP.1 integration for meeting today’s goal, Federated wireless worked out some fixes related to the review comments from us on PR #602. We have put the fixes in a sub-branch (MCP.1-fix) which is branched off from your “MCP.1” for not disturbing the ongoing work. If you would like to take these fixes, please review and merge this into "MCP.1" branch after approval. Or otherwise, you can ignore this PR and close it.
=> fix MCP.1 integration time errors - please read the description first.

src/harness/reference_models/pre_iap_filtering/pre_iap_filtering.py
This commit fixes run time error : “list indices must be integers, not str”
Noticed that ‘gwblRecords’ are not present in protected_entities and we are invoking pre-iap filtering with the same, so ensure 'gwblRecords' and 'fssRecords' are available.
=> fix run time error: list indices must be integers not str

src/harness/testcases/WINNF_FT_S_BPR_testcase.py
No change in fact since median is the default (and it was not specified before). 
But better to make it explicit.
This is related to change proposal: WINNF-18-I-00107
so far approved by everyone.
=> Border: Explicitely using median ITM pathloss

src/harness/testcases/WINNF_FT_S_FAD_testcase.py
The test_WINNF_FT_S_FAD_1 is incorrect when comparing FAD files retrieved by different SAS THs. The issues are as follows:
- Wrong dictionaries are being compared.
- The original FAD files are mutated (keys are being removed), and hence the comparison will never succeed. The fix is to create deep copies of the original FAD files. Alternative would be to add back the keys being removed - this complicates the logic though.
=> Fix test_WINNF_FT_S_FAD_1

cert/openssl.cnf, src/harness/certs/generate_fake_certs.sh
Update openssl config of SAS cert to use only one config with both server auth and client auth
> Hi, Reda, and all
Thanks Reda, I have studied some more. 
>BTW
I don’t know if there is a way to generate a certificate with both(server and client auth), I tried that before and I couldn’t make it work on windows :/
Yes I’m also thinking the same idea(below Option-2 solution). 
We haven’t try this, but if it can be done, that’s more easier to implement. 
I think the current MCP code can be used with small/no changes. 
We may need to change the openssl.conf (and generate_fake_certs.sh)
Below is thought in our team what is the problem and possible approach. 
(SAS-TH) ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: (SAS-UUT)
Client …
=> Update openssl config of SAS cert

src/harness/certs/generate_fake_certs.sh
script to generate certs was hanging up.
adding < /dev/null on line 584 so it will no longer hang up
=> Update generate_fake_certs.sh so it won't hang up

src/harness/testcases/testdata/gwpz_record_0.json
revert src/harness/testcases/testdata/gwpz_record_0.json back, no landcategory is needed for injecting into UUT according to the post-merge discussion in PR #617
=> revert src/harness/testcases/testdata/gwpz_record_0.json back

src/harness/reference_models/iap/iap.py
We have reviewed the IAP calculation and agreed that there is an issue as Navin pointed out. We found the root cause of the issue was related to the input parameter to calculatePostIapAggregateInterference(). We concluded that there is no need to account for  HM_p_s as per the below equation. The really issue was that the input to calculatePostIapAggregateInterference() API was wrong. Q_p – Mg_p (esc_iap_threshold value) was passed as input. It shall be corrected to pass Q_p (esc_thresh_q value). 
```
Qp        Ap
10---- - 10 ----                          
10        10                ASASp s
{------------------}    + 10 -----------
Nsas                   10
```
Please note, interf.IN_BAND_INSERTION_LOSS for ESC protection threshold was accommodated for channel frequencies greater than …
=> fix issue 651 - IAP calculation headroom margin issue

README.md, src/harness/README.md, src/harness/sas_test_harness.py, src/harness/security_testcase.py, src/harness/testcases/WINNF_FT_S_EPR_testcase.py, src/harness/testcases/WINNF_FT_S_FAD_testcase.py, src/harness/testcases/WINNF_FT_S_FDB_testcase.py, src/harness/testcases/WINNF_FT_S_FPR_testcase.py, src/harness/testcases/WINNF_FT_S_GPR_testcase.py, src/harness/testcases/WINNF_FT_S_GRA_testcase.py, src/harness/testcases/WINNF_FT_S_IPR_testcase.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py, src/harness/testcases/WINNF_FT_S_PCR_testcase.py, src/harness/testcases/WINNF_FT_S_PPR_testcase.py, src/harness/testcases/WINNF_FT_S_SCS_testcase.py, src/harness/testcases/WINNF_FT_S_SDS_testcase.py, src/harness/testcases/WINNF_FT_S_SIQ_testcase.py, src/harness/testcases/WINNF_FT_S_SSS_testcase.py, src/harness/testcases/WINNF_FT_S_WDB_testcase.py, src/harness/util.py
Clean code by introducing new function in util.py and use them whenever:
- getCertFilename(): moved from security_testcase,
- getFqdnLocalhost(): return the $HOSTNAME, allowing to run the tests on another computer than the SAS UUT
- getUnusedPort(): get rid of hardcoded port
=> Clean code by introducing new functions in util.py

src/harness/reference_models/common/data.py, src/harness/reference_models/iap/iap.py, src/harness/reference_models/iap/iap_example.py, src/harness/reference_models/interference/interference.py
Several bug fixes for IAP
General cleanup of the IAP module (aggregate_interference cleanup will follow):
- ESC data extraction done on single place in common/data.py (so will be reused in aggregate_interference and will avoid code duplication)
- FSS parameter extraction was wrong for tilt. Remove duplication by using the common/data.py routine already used elsewhere
- building the final post-IAP dictionary was wrong: the longitude was constantly erased and only one was kept per latitude (note that this expains some issues see in KeyError exception running MCP)
- general cleanup to use the common naming for variables, and improve the readability of the main IAP loop
=> IAP: bug fixes and cleanup

src/harness/reference_models/interference/aggregate_interference.py, src/harness/reference_models/interference/interference.py
- General cleanup of doc, 
- Reuse of the common/data.py routines: getFssInfo and getEscInfo  to avoid code duplication. 
This fixes some issues for FSS (tilt and AMSL). This code assume that the getEscInfo() routine has been 
added in common/data.py (see PR #662).
- Move the aggr_interference- only routine from interference.py module to aggregate_interference.py module.
=> Aggregate interference: Cleanup and bug fix

src/harness/reference_models/interference/aggregate_interference.py, src/harness/sas_testcase.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py
- Aggregate Interference results will now be populated for points with no grants (resolves issue in MCP interference checking).
- assertRegistered will now not exception if called with an empty list of registration requests (Allows MCP configurations containing iterations with zero CBSDs being added).
- Correct protected area calculation to only consider a point as correct if all frequencies are below the allowed threshold.
- Produce assert error if a protected entity with zero points is used (to help detect bad configs).
=> Fix minor bugs in MCP workflow

src/harness/sas_testcase.py, src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Allowing for SUUT to be able to fail directly on AssertPpaCreateFailure (TCs PCR 4 and 5)
Notice that fucntion existed in two places:
sas_testcase.py
PCR.py file
modified both...
seems like one of them could be removed
Also added a missing import on PCR file
=> PPA Assert Failure  adding ability for SUUT to fail right away  (PCR4 and PCR5)

src/harness/util.py
The way the schema_dir is build is not correct, and can possibly failed on mounted network filesystem
=> Fix schema validation: could failed on network filesystem.

src/harness/testcases/WINNF_FT_S_PCR_testcase.py
In PCR7 a zone is injected into the SUUT
/admin/injectdata/zone :
{"record": {"terminated": false, "name": "PPA Zone 0", "zone": {"type": "Polygon", "coordinates": [[[-100.61355286470628, 39.06028870255636], [-100.6103309414228, 39.05904150644663], [-100.60427196105131, 39.056756972863944], [-100.60425345765879, 39.05674997526318], [
This is not consistent with the zones we inject in other TCs:
/admin/injectdata/zone :
{"record": {"terminated": false, "name": "PPA Zone 0", "zone": {"type": "FeatureCollection", "features": [{"geometry": {"type": "Polygon", "coordinates": [[[-97.23861694335938, 38.865374851611634], [-97.31964111328125, 38.7615795117574], [-97.16995239257811, 38.739088441876866], [-97.16171264648436, 38.86751337001198], [-97.2386
It looks like the zone record in the PCR 7 …
=> Fw pcr.7fix

src/harness/sas_testcase.py, src/harness/testcases/WINNF_FT_S_SIQ_testcase.py, src/harness/testcases/helper_unit_testcase.py
This is fox fixing issue #639. Basically 
1. for C2, since CBSD C2 is out of every single protected entities and thus the full frequency range from 3550-3700 shall be available to be responded in spectrum inquiry response.
2. for C4, CBSD C4 is only in range of the FSS site with a GWBL, so we only need to exclude the GWBL-FSS frequency range and thus frequency range 3550-3650 shall be available to be responded in spectrum inquiry response.
The original codes will fail the tests when SAS respond single frequency range of 3550-3700 and 3550-3650 respectively.
Please review.
=> fix SIQ.3 C2 and C4 checking

src/harness/reference_models/interference/interference.py, src/harness/reference_models/propagation/wf_hybrid.py, src/harness/reference_models/propagation/wf_hybrid_test.py, src/harness/reference_models/propagation/wf_itm.py, src/harness/reference_models/propagation/wf_itm_test.py
Fix crash if Tx and Rx location are the same.
Also disable the return of the "internals" information which are not used anywhere as part of test harness.
This contains big arrays and prevent efficient caching of the propagation results.
=> Fix propagation segmentation fault when Tx & Rx location identical. 

src/harness/full_activity_dump_helper.py, src/harness/sas_testcase.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py
- Adds threading to allow CPAS and the IAP reference model to be done in parallel (CPAS is SAS UUT side, IAP is test harness side)
- Adds threading to allow FAD generation and IAP aggregate interference check to be done in parallel (FAD generation is SAS UUT side, aggregate interference check is test harness side)
- Adds threading to allow DPA movelist calculation and IAP aggregate interference check to be done in parallel (Both are test harness side but do not impact one another, and are potentially long running)
=> Add multi threading to MCP steps that can be run in parallel

src/harness/reference_models/interference/aggregate_interference.py, src/harness/reference_models/interference/interference.py, src/harness/reference_models/interference/interference_test.py
- Some FSS and GWPZ may not be aligned with a multiple of 5MHz. The generate channels to protect were then also unaligned. For example see the GWPZ database at:
https://opendata.fcc.gov/Wireless/ULS-3650-Locations/euz5-46g2/data
Line 9:   center freq 3661.5 MHz   bandwidth 6.94 MHz
- Add unit test on that function
- Add the frequency check that FSS high passband frequency beyond 3700MHz. This test is done in the IAP but not in aggregated interference code.
=> IAP/AggInterf: insure the protection channel aligned to multiple of 5MHz

src/harness/reference_models/interference/interference.py, src/harness/reference_models/interference/interference_test.py
Some FSS do not start at a multiple of 5MHz. 
Interference calculation need to take into account actual frequency overlap.
=> FSS cochannel: support partial overlap with grant

src/harness/database.py, src/harness/sas_test_harness.py, src/harness/test.cfg, src/harness/util.py, src/harness/util_test.py
Following discussion about getFqdnLocalhost()/getUnusedPort() in [Sas_test_dev]
Here the proposed solution, assuming Dorch comment about the ITS system architecture:
We assume that ITS will use a different machine for each SAS provider,
directly connected to internet to run the TH.
This machine has a firewall that open only a limited contiguous number of ports.
The previous solution of using 'random available' port sdon't fit this configuration.
Also it can produce problem with generated config file where the saved port became
unavailable.
The new proposed solution:
- we use a configured range of port, that must be keep available only for the TH
- in each webserver implementation (database.py, sas_test_harness.py), we:
- always use '' when creating the server socket to listen to all …
=> Fix for getFqdnLocalhost()/getUnusedPort()

src/harness/reference_models/pre_iap_filtering/testdata/gwpz_0.json, src/harness/reference_models/pre_iap_filtering/zone_purge.py
Fix the below issue found by Takashi
[1] zone_purge.py  ['record'] is missing. 
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/reference_models/pre_iap_filtering/zone_purge.py
pre_iap_util.purgeOverlappingGrants(cbsds_within_gwpz,
#gwpz_record['deploymentParam'][0]
gwpz_record['record']['deploymentParam'][0]
['operationParam']['operationFrequencyRange'])
=> fix issue #721 part [1]

src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Fix the issue reported as below
======================================================================
ERROR: test_WINNF_FT_S_PCR_7_0_default (testcases.WINNF_FT_S_PCR_testcase.PpaCreationTestcase)
Overlapping PPA Boundaries.
----------------------------------------------------------------------
Traceback (most recent call last):
File "util.py", line 79, in _func
return func(*a, config_filename=config)
File "testcases/WINNF_FT_S_PCR_testcase.py", line 991, in test_WINNF_FT_S_PCR_7
self.assertPpaCreationFailure(ppa_creation_request)
File "testcases/WINNF_FT_S_PCR_testcase.py", line 210, in assertPpaCreationFailure
timeout = datetime.now() + timedelta(hours=2)
NameError: global name 'datetime' is not defined
=> fix the datetime missing error

src/harness/reference_models/common/mpool.py, src/harness/reference_models/iap/iap.py, src/harness/reference_models/interference/aggregate_interference.py, src/harness/reference_models/interference/interference.py, src/harness/reference_models/tools/benchmark/prof_agg_interf.py, src/harness/reference_models/tools/benchmark/prof_prop.py, src/harness/reference_models/tools/profpool.py
+ Remove the use of the mp Manager, and using the pool mechanism instead.
Some profiling of the Manager as used in the code shows that it does not
scale at all, as it constantly fork new process and lock during
contention when updating the shared dict (plus IPC overheads).
As a consequence, beyond a few processes, the actual running time is
constant or actually increase. All gains from parallel calculation is
lost on the shared objects management, which can take typically:
- 60% for 4 processes 
- 85% for 12 processes
- and so on..
Using simply the regular returned value from pool.map is much more
scalable, in addition of being simple.
+ Add profile script in tools/benchmark + a `profpool.py` utility in tools/
to enable the ability to profile each process. To run, simply launch the …
=> Remove multiprocess Manager

src/harness/reference_models/dpa/dpa_mgr.py, src/harness/reference_models/dpa/dpa_mgr_test.py, src/harness/reference_models/geo/zones.py
DPA KML are not yet finalized in the sense that:
- all mandatory OOB neighbor distances are currently set as NaN
- the catA optional distance is also set to NaN instead of either being specified or left blank
This second point means that the code was using a NaN distance for CatA, and this breaks IPR2: 
you then have CatA CBSD in Oregon being in neighborhood of east coast DPA. 
Running such long range path loss calculation is extremely slow obviously as a lot of terrain tiles need to be loaded.
In addition fixed the channelization of the DPA channel for the case where the DPA bandwidth are not multiple of 10MHz. Although they are all in the current DPA KML, the original list of inland DPAs had radar operating only in small frequency band of few MHz. This change will support these cases if …
=> Fix IPR2 issue caused by temporary DPA KML

src/harness/certs/generate_fake_certs.sh, src/harness/certs/generate_sas_cert.sh
(1) Fixes the problem where root/ was deleted in generate_fake_certs.sh but required by generate_sas_cert.sh.
(2) Adds SAN support to generate_sas_cert.sh.
(3) Now also generates an ECC cert for SAS UUT.
(4) Fixes the filenames of the SAS UUT certs so that they do not overwrite certs generated by generate_fake_certs.sh.
=> Updates the cert generation scripts:

src/harness/reference_models/common/data.py, src/harness/reference_models/iap/iap.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py
The absolute threshold need to be scaled to be relative to same
bandwidth as the one used for aggregate interference calculation,
ie IAP_BW (5MHz) in most cases, except for FSS blocking where it
is a general threshold.
=> Fix xPR tests for interference check when no peer SAS.

src/harness/reference_models/dpa/dpa_mgr.py, src/harness/reference_models/dpa/dpa_mgr_example.py, src/harness/reference_models/dpa/move_list.py, src/harness/reference_models/iap/iap.py, src/harness/reference_models/interference/aggregate_interference.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Current logging is either too extensive (IAP aggr interference check) or not enough (DPA).
For facilitating the analysis of the testcases, improved the INFO logging, and the WARNING/DEBUG logging.
Note one minor addition in the dpa_mgr to store the DPA name in the object, as it is useful in the log.
=> Improved logging for DPA and IAP aggr interference

src/harness/reference_models/interference/interference.py
The special CatA with ESC case was done with the implicit assumption
that the channels are the 5MHz IAP channels. The code works in that
case (for example: aggregateInterference check).
But the IAP runs the overlap selection using the whole ESC band
3550-3680 to filter the grants in the neighborhood. The code was not
working in that condition and CatA beyond 3660 were kept in the
neighborhood, preventing the IAP loop to ever converge.
=> Bug fix on the ESC neighborhood for CatA during IAP.

src/harness/testcases/WINNF_FT_S_EPR_testcase.py, src/harness/testcases/WINNF_FT_S_FAD_testcase.py, src/harness/testcases/WINNF_FT_S_FPR_testcase.py, src/harness/testcases/WINNF_FT_S_GPR_testcase.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py, src/harness/testcases/WINNF_FT_S_PPR_testcase.py
- add simple MCP check for initial cbsdRequests
- update FAD.2 device 4, so the Eirp of its Grant is reduced after CPAS(the reference model result now for this grant is 12 dBm)
=> add simple MCP check and update FAD.2 device 4

src/harness/testcases/WINNF_FT_S_PCR_testcase.py
1. Change device_c heightType to 'AGL' in PCR_1, PCR_2 and PCR_4.
2. Change device_c location in PCR_1
=> Fix device_c heightType and location for a contour with a testable signal level.

src/harness/reference_models/geo/nlcd.py
...even when the NLCD data isn't available (uses the default value instead). Without this change, GWPZs in e.g. Hawaii will cause the test harness to crash.
=> By default, allow NLCD voting

src/harness/testcases/WINNF_FT_S_MCP_testcase.py
- Check for a DPA being already active (and skip its activation if that is the case, will log a warning but continue running the test)
- Deactivate DPAs in the dpaDeactivationList
=> Trigger DPA activation correctly in MCP.1

src/harness/reference_models/geo/utils.py, src/harness/reference_models/geo/utils_test.py
A minus was missing. As a consequence the default PPA for PCR3 and PCR7 are expanded instead of shrinked (and vice versa for PCR6)
=> Fix  ShrinkAndCleanPolygon to actually shrink and not expand.

src/harness/testcases/WINNF_FT_S_FDB_testcase.py
The maxEirp is set to zero, and hence the corresponding grant will not be terminated, since the aggregate interference to the FSS site is below threshold. 
Removed the lines setting the maxEirp so that the default value (10) is used. Verified that with that change the aggregate interference is exceeded.
=> Fixes invalid configs for FDB_3 and FDB_8.

src/harness/reference_models/propagation/wf_hybrid.py
By fixing the 'return_internals' option in wf_hybrid model.
This option avoids outputing the internal data, and was introduced
to avoid using too much memory use, when using caching within the IAP.
Unfortunately the logic was not quite right and the internals extensive
data were returned (and so cached within IAP) even by default.
This PR fixes this as it is intended to be
=> IAP propag cache: avoid excessive memory use 

src/harness/sas_testcase.py, src/harness/testcases/WINNF_FT_S_PCR_testcase.py
When the softer method of checking was added a while back it was only done for the PPa creation cases where creation was successful.
Went ahead and added it to the cases where the creation would result in a failure.
Also removed duplicate function that was on PCR py file
=> Adding less stringent check to PPA creation on assertppacreationfailure function

src/harness/testcases/WINNF_FT_S_FDB_testcase.py
update FDB4 default config so the second CBSD on the first check also allows a response code of 501
=> Adding 501 as a valid response code to 2nd CBSD in first check for FDB4 default config

src/harness/testcases/WINNF_FT_S_IPR_testcase.py
The default config activates East4 which is approx. 2278 km from the CBSD and hence its grants are not affected. Changing the config to activate East3, which is approx. 65 km away so that the grant is on the move list and hence the transmitExpireTime is updated as expected.
=> Fixes the default config for IPR_5

src/harness/testcases/WINNF_FT_S_FDB_testcase.py
When SAS UUT Responded with Interference in Grant Response, there's no need for Relinquishment.
=> FDB.6: Skip Relinquishment in case of Interference Response in Grant

src/harness/database.py, src/harness/sas_test_harness.py, src/harness/sas_testcase.py, src/harness/testcases/WINNF_FT_S_EPR_testcase.py, src/harness/testcases/WINNF_FT_S_FAD_testcase.py, src/harness/testcases/WINNF_FT_S_FDB_testcase.py, src/harness/testcases/WINNF_FT_S_FPR_testcase.py, src/harness/testcases/WINNF_FT_S_GPR_testcase.py, src/harness/testcases/WINNF_FT_S_GRA_testcase.py, src/harness/testcases/WINNF_FT_S_IPR_testcase.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py, src/harness/testcases/WINNF_FT_S_MES_testcase.py, src/harness/testcases/WINNF_FT_S_PPR_testcase.py, src/harness/testcases/WINNF_FT_S_WDB_testcase.py
Added Server Shutdown as a part of Teardown. While running tests in Bulk Ports get exhausted, this fix will stop the servers if they are running in between tests.
=> Fix Server Shutdown between Tests

src/harness/testcases/WINNF_FT_S_BPR_testcase.py
Use the right grant request (and corresponding maxEirp) in the interference calculation. The existing code uses the wrong index into the grant requests array and hence there is a mismatch between the EIRP used in the SAS calculation vs. the EIRP used in the test harness calculation.
=> Use the right grant request & maxEirp in the interference calculation.

src/harness/test_harness_objects.py
Fix bug where the heartbeat request was used rather than the heartbeat response when constructing the subsequent grant request.
=> Fix bug where the heartbeat request was used rather than the heartbeat response

src/harness/test_harness_objects.py
We agreed long ago in test dev that we would set grantRenew=True in each heartbeat request made during the functional test cases, thus allowing the SAS Admin to set a relatively short grant duration (important for reducing the runtime of HBT.6) without unintended consequences (e.g. the grant expiring in the middle of MCP.1). This PR adds this functionality, which was inadvertently omitted.
=> Renew grants with every heartbeat in functional tests

src/harness/reference_models/dpa/dpa_mgr.py, src/harness/reference_models/dpa/dpa_mgr_example.py
Wen one does not call ComputeMoveLists(), the internal state of DPA manager is not coherent.
MCP type harness test only perform CheckInterference when no peer SAS causes a test crash.
The fix is to :
- always have a coherent list of neighbor_list and move_list with the number of channels, and do not depend on ComputeMoveLIst being called
- make sure the self.channels is a private variable (renaming it to self._channels) as client code shall not manipulate this directly.
=> Fix DPA manager to have coherent state always.

src/harness/test_harness_objects.py
- Fix call to _relinquishmentRequestWithMaximumBatchSize to use self (without it the code will fail if a grant is relinquished on heartbeat).
- Remove incorrect error message when a heartbeat terminates a grant but does not provide operationParam. This is a valid response as a SAS is not required to provide operationParam, the current error message suggests such a response is invalid.
=> Fix miscellaneous bugs in domain proxy

src/harness/reference_models/pre_iap_filtering/fss_purge.py
In Purge list, the threshold is established according to a 5MHz band at 3700-3705.
However the generated interference in that band is counted only for a 1MHz bandwidth
(since the MCBSD is for 1 MHz reference). This PR fixes the MCBSD to count for
the full 5MHz channel.
=> Fix FSS purge list: MCBSD should be for the 5MHz target band.

src/harness/security_testcase.py, src/harness/testcases/WINNF_FT_S_SCS_testcase.py, src/harness/testcases/WINNF_FT_S_SDS_testcase.py, src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Call the assertTls*() functions with a base_url that matches a function
that the test is already using.
In practice, this means:
- SCS and SDS tests use cbsd_sas_active_base_url
- SSS tests use sas_sas_active_base_url
Fixes #803
=> Make base_url a parameter to assertTlsHandshakeFailure().

src/harness/testcases/WINNF_FT_S_FDB_testcase.py
With the existing code, `current_time` correctly uses PDT but `scheduled_cpas_start_time` and `scheduled_cpas_end_time` uses LMT, which ultimately causes the test harness to wait too long for CPAS to complete. This change corrects the timezone discrepancy.
=> Fix time zone issue in FDB.8

src/harness/testcases/WINNF_FT_S_DRG_testcase.py
Update DRG 6 so the test doesn't send preload conditional data for registrated CBSD(not successfully deregistered CBSDs)
=> DRG.6 remove registered CBSDs from second preload conditional data

src/harness/reference_models/propagation/ehata/its/ExtendedHata.cpp, src/harness/reference_models/propagation/ehata/its/FindHorizons.cpp, src/harness/reference_models/propagation/ehata/its/FindQuantile.cpp, src/harness/reference_models/propagation/ehata/its/FineRollingHillyTerrainCorectionFactor.cpp, src/harness/reference_models/propagation/ehata/its/GeneralSlopeCorrectionFactor.cpp, src/harness/reference_models/propagation/ehata/its/IsolatedRidgeCorrectionFactor.cpp, src/harness/reference_models/propagation/ehata/its/LeastSquares.cpp, src/harness/reference_models/propagation/ehata/its/MedianBasicPropLoss.cpp, src/harness/reference_models/propagation/ehata/its/MedianRollingHillyTerrainCorrectionFactor.cpp, src/harness/reference_models/propagation/ehata/its/MixedPathCorrectionFactor.cpp, src/harness/reference_models/propagation/ehata/its/PreprocessTerrainPath.cpp, src/harness/reference_models/propagation/ehata/its/ehata.h
Previously to avoid having the code base differing too much from
the original ITS reference implementation, we defined a global
#define float double
in the ehata.h header file.
Obviously this is very hack and can fail depending on the order of
inclusion of ehata.h, or if t is forgotten in one of the cpp file.
The proper way is now implemented by directly changing all `float`
occurence with `double`.
This is in line with the change made by ITS on their reference
implementation at:
https://github.com/NTIA/ehata/commit/df2b5802f1444b77ffadf4a4301c5b2fd7be691c
=> EHata: Cleanup of the float -> double switch.

src/harness/testcases/WINNF_FT_S_DRG_testcase.py, src/harness/testcases/WINNF_FT_S_GRA_testcase.py, src/harness/testcases/WINNF_FT_S_REG_testcase.py, src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
There are no functional changes in this PR. Instead, it proposes to collect information on multiple failures before halting the test, allowing for faster debugging in the presence of multiple errors. It also logs additional information which may be useful during debugging.
=> Add additional debugging information to some of the protocol tests.

src/harness/reference_models/dpa/dpa_mgr.py
The output of calcAggregatedInterference() is effectively a scalar in the case where there are no CBSDs in the neighborhood, and this case was not accounted for in the previous version of the logging code.
This fix addresses that issue, and more gracefully catches errors in the new logging code so that the test case may proceed even if the logging fails (though an error will be logged, of course).
=> Fix DPA logging for "no grants in neighborhood" case

src/harness/test_harness_objects.py
Without this change, the injection of conditional registration data does not follow the batching methodology we've established for other APIs.
=> Batch conditional reg data

src/harness/request_handler.py
As suggested by Sony, this change prevents the connection from dropping which would cause a test failure.
=> Add TCP keepalive to all test harness requests

src/harness/testcases/WINNF_FT_S_IPR_testcase.py, src/harness/testcases/WINNF_FT_S_MCP_testcase.py
This allows us to collect the maximum amount of information for later analysis.
**DO NOT SUBMIT this PR until after WG4 has approved the change to the test spec.** For now, this PR is made available for early review and for convenience to SAS Admins while evaluating DPA protection criteria.
=> Wait until the very end to fail tests which check aggregate interference to DPAs

src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Added peer fccid injection for IPR testcases. This is related to Whitelist fccIds by injecting before FAD Issue #810
=> Peer fccid injection for IPR testcases

src/harness/reference_models/propagation/itm/itm_its_py.cpp
Affects the calculations with array or reliabilities (like DPA),
and average computed value.
The mem leak is expected to be about 16kB for a DPA CBSD-Point link,
and 800 bytes for a CBSD-point link in other protection type.
It is thus quite bug for DPA and affect negatively any test of the test harness
=> Fix mem Leak on ITM

src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Fixes https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/822
Adhering to [SAS-CBSD specification WINNF-TS-0016, Version V1.2.2, 1 October 2018](https://workspace.winnforum.org/higherlogic/ws/public/download/7279/WINNF-TS-0016-V1.2.2%20SAS%20to%20CBSD%20Technical%20Specification.pdf) which says:
"Latitude of the CBSD antenna location in degrees relative to the WGS 84 datum [n.11]. The allowed range is from -90.000000 to +90.000000. Positive values represent latitudes north of the equator; negative values south of the equator. Values are specified using 6 digits to the right of the decimal point."
This should not affect the latitude or longitude precision elsewhere.
=> for FAD_1, consider lat and lng equal if same to 6 decimal places ( Fixes #822 )

src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Fix tiny bug for MCP test when the config contains multi FSS at least one of them is for FPR.3 scenario(i.e FSS with TTC false and out of band).
spec : [WINNF.FT.S.FPR.3] Multiple CBSDs from Multiple SASs Inside and Outside the Neighborhood of an FSS Station for “FSS Scenario 2” with TT&C Flag = OFF
=> Tiny fix to treat not handledFSS Scenario 

src/harness/sas_test_harness.py
FAD.2 generates default.config with empty "cbsdReferenceId": [].
According to [WINNF-TS-0096 v1.3.0 SAS-SAS Protocol spec](https://workspace.winnforum.org/higherlogic/ws/public/document?document_id=6482), section 8.5.1 PPA Information Object definition mentions that _cbsdReferenceId_ field is a _"List of one or more CBSD Reference IDs in the cluster list of the PPA"_.
So _ppa_record['ppaInfo']['cbsdReferenceId']_ should also be updated if it's an empty array.
=> update if PPA cbsd_reference_id is empty array in sas_test_harness.py generatePpaRecords()

src/harness/reference_models/dpa/dpa_mgr.py, src/harness/reference_models/dpa/move_list.py, src/harness/test_main.py
Some logs were introduced in DPA CheckInterference for better post analysis of result in #830.
This PR improves this logging according to various report received since then:
- output of CSV logs put into harness/testcases/output/
- output the neighbor list in addition of the keep list, to allow full post processing analysis (for example redo random movelist with ref model and anlayse agg interference variation)
- fix issues with SAS UUT keep list to be the keep list per channel and not all SAS active grants in whole US for all channels. This means we run the active grants through a neighbor filter, just used for that. 
- main test harness script can now be run in debug mode by adding option: --log_level=debug
=> DPA: improve logs for enabling post processing eval

src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Previously, we required that the extra (non-utilized) protected entity fields be *absent* in an xPR config; now we permit them as long as they do not actually contain any entities. For example, an EPR config may now also contain the field 'gwpzRecords' so long as there are no actual GWPZ records configured.
This change is to fulfill a request by ITS which will allow them to leverage their existing MCP config generation code to create valid xPR configs. This PR does not contain any substantive changes.
To quickly double-check that your custom configs remain valid after this change -- which should be the case for all previously-valid configs -- put a `return` statement on line 225 to bypass actual execution of MCP (i.e. the test will exit immediately after checking the config). I have …
=> Relax the checks on xPR configs (still matches spec)

src/harness/reference_models/common/data.py
=> # small update of reference model to use "requestedOperationParam" of grant records in dump

src/harness/reference_models/dpa/dpa_builder.py, src/harness/reference_models/dpa/dpa_mgr_example.py
The check routine will raise exception as they assume a MultiPoint.
Note: this is usually not the case that one use a single point for a DPA, except for testing purpose. 
This fix was requested by ITS so they can more easily debug which point create some issue they see.
=> Fix DPA builder to work with single point in one DPA area.

src/harness/reference_models/dpa/dpa_mgr.py, src/harness/reference_models/dpa/dpa_mgr_test.py, src/harness/reference_models/dpa/move_list.py
Simply make sure that the "inside DPA" grants are included in the proper move list
after the regular processing:
- for inband channel, include all the grant which overlaps
- for OOB, include all the grants 
This method insures that we would get same move list results as if we were adding 
protection points exactly under each CBSD. 
Note that initial implementation was proposing to first filter out the grants inside the DPA and then run
the move list on the remaining outside grants. This is somewhat a bit more optimal in theory, 
although we do not expect a major difference in practice. It has the disadvantage of changing 
a bit more the philosophy of the move list algorithm, and thus requires handling a special case.
Adding unit test on the logic implemented. 
And for sake of improving …
=> DPA: properly support grants within  DPA

src/harness/reference_models/dpa/dpa_mgr.py, src/harness/reference_models/dpa/dpa_mgr_test.py, src/harness/reference_models/dpa/move_list.py
Previous PR has introduced special code to include all inside grants
in move list and neighbor list.
Unfortunately this let the logger used for analysing DPA margin failures
not perfectly in line. The SAS_UUT active list of grants (reported to
the log only) would not show some of the inside grants.
This PR fixes that.
Note that this PR has no effect whatsoever on the DPA operation, just on
the logging that is used for post analysis (only when required because
of a failure), possibly with provided script:
tools/studies/dpa_margin_sim.py.
=> DPA: Fix the CheckInterference loggers for "inside" grants.

src/harness/reference_models/geo/zones.py
Bunch of committed test (IPR and FDB2) relies on non compliant DPA KML.
A previous change has removed varous hacks to support those non
compliant KML, and as such those test fails to run.
For the sake of backward compatibility, add back the hacks.
=> Revert zones.py change.

src/lib/geo/README.md, src/lib/geo/geo_utils.py, src/lib/geo/geo_utils_test.py, src/studies/esc_impact_pop/README.md, src/studies/esc_impact_pop/esc_pop_impact.py
New mode `--nbor_pop_only' for computing full population in sensor neighborhood, in order to play with various statistics.
Usage:
python esc_pop_impact.py --esc_fads=testdata/esc_test.json --nbor_pop_only
Also minor cleanup by moving geo_utils in its own library module.
=> esc_pop_impact: new mode  for computing full pop within neighborhood

src/harness/certs/generate_short_lived_certs.sh, src/harness/request_handler.py, src/harness/security_testcase.py, src/harness/util.py, src/harness/util_test.py
Code migration for Python3: ensure S[CDS]S testcases running under python 3.7 and openSSL 1.1.1
=> Fix running S[CDS]S testcases under python 3.7 + OpenSSL 1.1.1

src/harness/util2.py
`util2.py` increments and decrements just the Year for Start and End dates.
However, this fails for Leap Day (Feb. 29) since this date doesn't exist in the preceding and subsequent years.
Suggesting instead to increment and decrement the date by 365 days using timedelta.
fixes #912
=> fix Leapday bug - Just changing Year does not work for Feb 29
